# SPDX-License-Identifier: GPL-2.0

TEST_INCLUDES := \
	../lib/sh/dpll_lib.sh \
	../../../net/lib.sh \
# end of TEST_INCLUDES

TEST_PROGS := \
	dpll_basic.sh \
	dpll_stress.sh \
# end of TEST_PROGS

include ../../../lib.mk
